stages:
- build
- deploy

variables:
  PUBLIC_URL: /sia-watermarking
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_VERSION: 18.5.0
  NPM_VERSION: 8.13.2
  NVM_DIR: /root/.nvm

cache:
  paths:
  - build

build:
  image: emscripten/emsdk:3.1.15
  stage: build
  before_script:
  - apt-get update && apt-get -y install autoconf libtool
  - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  - . /root/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - npm install -g npm@$NPM_VERSION
  - node -v
  - npm -v
  script:
  - npm install
  - make
  - npm run build
  - echo Build successful!
  artifacts:
    expire_in: 30 mins
    paths:
    - ./build
    - /root/.npm/_logs

pages:
  image: node:18.4.0-alpine3.15
  stage: deploy
  before_script:
  - mv public _public
  - mv build public
  - cp public/index.html public/404.html
  script:
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public
