stages:
- build
- deploy

variables:
  PUBLIC_URL: /sia-watermarking
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_VERSION: 18.5.0
  NVM_DIR: /root/.nvm

cache:
  paths:
  - build

build:
  image: emscripten/emsdk:3.1.15
  stage: build
  before_script:
  - node -v
  - npm -v
  - uname -a
  - apt-get update && apt-get -y install autoconf libtool
  - apt-get update && apt-get install wget curl ca-certificates rsync -y
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
  - . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
  - . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
  - cp /root/.nvm/versions/node/v${NODE_VERSION}/bin/node /usr/bin/
  - cp /root/.nvm/versions/node/v${NODE_VERSION}/bin/npm /usr/bin/
  - /root/.nvm/versions/node/v${NODE_VERSION}/bin/npm install leasot@latest -g
  - nvm --version
  - node -v
  - npm -v
  - npm install
  - make
  script:
  - npm run build
  - make
  - echo Build successful!
  artifacts:
    expire_in: 30 mins
    paths:
    - ./build

pages:
  image: node:18.4.0-alpine3.15
  stage: deploy
  before_script:
  - mv public _public
  - mv build public
  - cp public/index.html public/404.html
  script:
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public
