stages:
- build
- deploy

variables:
  PUBLIC_URL: /sia-watermarking
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - build

build:
  image: emscripten/emsdk:3.1.15
  stage: build
  before_script:
  - node -v
  - apt-get update && apt-get -y install autoconf libtool nodejs
  - node -v
  - npm install
  - make
  script:
  - npm run build
  - make
  - echo Build successful!
  artifacts:
    expire_in: 30 mins
    paths:
    - ./build

pages:
  image: node:18.4.0-alpine3.15
  stage: deploy
  before_script:
  - mv public _public
  - mv build public
  - cp public/index.html public/404.html
  script:
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public
