stages:
- build
- deploy

cache:
  paths:
  - build

build:
  image: node:latest
  stage: build
  before_script:
  - npm install
  script:
  - npm run build 
  - echo Build successful!
  artifacts:
    expire_in: 30 mins
    paths:
    - ./build

pages:
  image: node:18.4.0-alpine3.15
  stage: deploy
  before_script:
  - rm -rf public
  - mv build public
  script:
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public
